# Generated by Django 5.1.2 on 2024-11-19 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_remove_blogpost_updated_at_alter_blogpost_author_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
